version: '3'

services:
  php:
    container_name: php
    build: .
    tty: true
    volumes:
      - ./src:/var/www/html
    networks:
     - default

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: top_secret
      MYSQL_DATABASE: twitter
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitter
    restart: unless-stopped
    tty: true
    ports:
      - "3406:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - default

  artisan:
    container_name: artisan
    build: .
    entrypoint: [ "php", "/var/www/html/artisan" ]
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - default

  npm:
    container_name: npm
    image: node:13.7-alpine
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - default

networks:
  default:
    driver: bridge